Repository monsieurbiz/SyliusAntiSpamPlugin, pull requests merged in 2021-02, with the labels that each got.

#2 Add PHP MD tests in tests github action
  .github/workflows/tests.yaml
Labels: Status: needs review, quick win

#3 Setup the QuarantineItem entity
  recipes/dev/config/packages/monsieurbiz_sylius_anti_spam_plugin.yaml
  src/Entity/QuarantineItem.php
  src/Entity/QuarantineItemInterface.php
  src/Migrations/Version20210225113648.php
  src/Resources/config/app/doctrine_migrations.yaml
  src/Resources/config/config.yaml
  src/Resources/config/doctrine/QuarantineItem.orm.xml
  src/Resources/config/sylius/resource.yaml
Labels: Priority: high, Status: needs review

#4 The customer can now fetch it's own quarantine item
  README.md
  src/Entity/CustomerQuarantineItemAwareTrait.php
  src/Resources/config/doctrine/QuarantineItem.orm.xml
  tests/Application/config/packages/_sylius.yaml
  tests/Application/src/Entity/Customer.php
Labels: Priority: high, Status: needs review, enhancement

#5 Add captcha field on register and contact pages
  composer.json
  phpunit.xml.dist
  src/Form/Extension/ContactFormExtension.php
  src/Form/Extension/CustomerRegistrationFormExtension.php
  src/Resources/config/config.yaml
  src/Resources/config/services.yaml
  src/Resources/config/sylius/ui.yaml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/Shop/form_captcha.html.twig
  symfony.lock
  tests/Application/.env
  tests/Application/config/bundles.php
  tests/Application/config/packages/karser_recaptcha3.yaml
Labels: Status: needs review

#6 Update README
  README.md
Labels: Priority: low, Status: needs review, quick win

#7 The license file is LICENSE.txt
  .php_cs.dist
  LICENSE.txt
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/MonsieurBizSyliusAntiSpamExtension.php
  src/Entity/CustomerQuarantineItemAwareTrait.php
  src/Entity/QuarantineItem.php
  src/Entity/QuarantineItemInterface.php
  src/Form/Extension/ContactFormExtension.php
  src/Form/Extension/CustomerRegistrationFormExtension.php
  src/Migrations/Version20210225113648.php
  src/MonsieurBizSyliusAntiSpamPlugin.php
  tests/Application/public/index.php
  tests/Application/src/Entity/Customer.php
  tests/Application/src/Kernel.php
  tests/Behat/DemoContext.php
  tests/bootstrap.php
Labels: Priority: low, Status: needs review, quick win

#9 Validators registry
  src/DependencyInjection/AddValidatorsPass.php
  src/DependencyInjection/MonsieurBizSyliusAntiSpamExtension.php
  src/MonsieurBizSyliusAntiSpamPlugin.php
  src/Registry/ValidatorsRegistry.php
  src/Registry/ValidatorsRegistryInterface.php
  src/Resources/config/services.yaml
  src/Validator/ReCaptcha3Validator.php
  src/Validator/ValidatorInterface.php
Labels: Priority: high, Status: needs review

#10 Fix PHP CS
  src/DependencyInjection/AddValidatorsPass.php
  src/Registry/ValidatorsRegistry.php
  src/Registry/ValidatorsRegistryInterface.php
  src/Validator/ReCaptcha3Validator.php
  src/Validator/ValidatorInterface.php
Labels: Status: needs review, quick win

#11 Add a level to a quarantine item
  src/Entity/QuarantineItem.php
  src/Entity/QuarantineItemInterface.php
  src/Migrations/Version20210226111417.php
  src/Resources/config/doctrine/QuarantineItem.orm.xml
Labels: Priority: high, Status: needs review, quick win

#12 Add QuarantineItemAwareInterface and Trait
  src/Entity/QuarantineItem.php
  src/Entity/QuarantineItemAwareInterface.php
  src/Entity/QuarantineItemAwareTrait.php
  src/Entity/QuarantineItemInterface.php
  src/Migrations/Version20210226114003.php
  src/Resources/config/doctrine/QuarantineItem.orm.xml
  tests/Application/src/Entity/Customer.php
Labels: Priority: high, Status: needs review

#13 Decorate Sylius Email Sender
  src/Email/Sender.php
  src/Resources/config/services.yaml
Labels: Priority: high, Status: needs review, quick win

#15 Be able to retrieve all validators in registry
  src/Registry/ValidatorsRegistry.php
  src/Registry/ValidatorsRegistryInterface.php
Labels: Status: needs review, quick win

#14 Change reasonCode to reasonCodes in Quarantine Item
  src/Entity/QuarantineItem.php
  src/Entity/QuarantineItemInterface.php
  src/Migrations/Version20210226145318.php
  src/Resources/config/doctrine/QuarantineItem.orm.xml
Labels: Status: needs review, quick win

#16 Do not send emails if quarantined
  src/Email/Sender.php
  src/Entity/QuarantineItem.php
  src/Entity/QuarantineItemInterface.php
  src/Migrations/Version20210226145055.php
  src/Repository/QuarantineItemRepository.php
  src/Repository/QuarantineItemRepositoryInterface.php
  src/Resources/config/doctrine/QuarantineItem.orm.xml
  src/Resources/config/sylius/resource.yaml
  tests/Application/config/packages/dev/swiftmailer.yaml
Labels: Priority: high, Status: needs review

#17 Add column with quarantine value on customers grid
  src/Resources/config/config.yaml
  src/Resources/config/sylius/grid.yaml
  src/Resources/translations/messages.en.yaml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yaml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/Admin/Grid/Field/quarantine_item.html.twig
  src/Resources/views/Shop/form_captcha.html.twig
Labels: Priority: high, Status: needs review

#18 Use health checker to create quarantine items
  src/Checker/HealthChecker.php
  src/Checker/HealthCheckerInterface.php
  src/Entity/QuarantineItemAwareInterface.php
  src/Entity/QuarantineItemAwareTrait.php
  src/EventListener/QuarantineItemAwareListener.php
  src/Registry/ValidatorsRegistry.php
  src/Registry/ValidatorsRegistryInterface.php
  src/Resources/config/services.yaml
Labels: Status: needs review
